version: "3.3"

services:
  redis:
    image: redis
    container_name: ${AI_MF_REDIS_CONTAINER_NAME}
    restart: always
    networks:
      - network
    volumes:
      - ai_mf_redis_data:/data

networks:
  network:
    name: ${AI_MF_IMAGE_NAME}


volumes:
  ai_mf_redis_data: