# Generated by Django 5.1.1 on 2024-10-07 12:03

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'annual_income',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='InvestmentAmountPerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount_per_year', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investment_amount_per_year',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marital_status',
            },
        ),
        migrations.CreateModel(
            name='MonthlySavingCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_category', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'monthly_saving_capacity',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'occupation',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=500)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section')),
            ],
            options={
                'db_table': 'response',
            },
        ),
        migrations.CreateModel(
            name='ConditionalQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visibility', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('dependent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_question', to='app.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_question', to='app.question')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.response')),
            ],
            options={
                'db_table': 'conditional_question',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section'),
        ),
        migrations.CreateModel(
            name='UserContactInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[app.models.validate_mobile_number])),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_contact_info',
                'indexes': [models.Index(fields=['email'], name='user_contac_email_f59fcd_idx'), models.Index(fields=['mobile_number'], name='user_contac_mobile__5846b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFinancialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_source_of_income', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('lock_in_period_accepted', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('investment_style', models.CharField(choices=[('SIP', 'SIP'), ('Lump-Sum', 'Lump-Sum')], default='SIP', max_length=10)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('annual_income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.annualincome')),
                ('investment_amount_per_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.investmentamountperyear')),
                ('monthly_saving_capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.monthlysavingcapacity')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.occupation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercontactinfo')),
            ],
            options={
                'db_table': 'user_financial_details',
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('otp_valid', models.DateTimeField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercontactinfo')),
            ],
            options={
                'db_table': 'user_otp',
            },
        ),
        migrations.CreateModel(
            name='UserPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.gender')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.maritalstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercontactinfo')),
            ],
            options={
                'db_table': 'user_personal_details',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.response')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercontactinfo')),
            ],
            options={
                'db_table': 'user_response',
            },
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_details', models.JSONField()),
                ('device_type', models.CharField(max_length=100)),
                ('last_access', models.DateTimeField()),
                ('action', models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('signed_up', 'Signed Up'), ('invalid', 'invalid_action')], default='invalid', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercontactinfo')),
            ],
            options={
                'db_table': 'user_logs',
                'indexes': [models.Index(fields=['user'], name='user_logs_user_id_2c9228_idx')],
            },
        ),
    ]
