# Generated by Django 5.0.7 on 2024-09-12 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(db_index=True, max_length=255)),
                ('ip_details', models.JSONField()),
                ('device_type', models.CharField(max_length=100)),
                ('last_access', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_logs',
                'indexes': [models.Index(fields=['email_id'], name='user_logs_email_i_942fc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_valid_till', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_management',
                'indexes': [models.Index(fields=['email'], name='user_manage_email_55611d_idx')],
            },
        ),
    ]
