# Generated by Django 5.0.7 on 2024-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='action',
            field=models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('invalid', 'invalid_action')], default='invalid', max_length=10),
        ),
    ]
