# Generated by Django 5.0.7 on 2024-09-26 10:25

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlogs",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[app.models.validate_mobile_number],
            ),
        ),
        migrations.AlterField(
            model_name="usermanagement",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[app.models.validate_mobile_number],
            ),
        ),
    ]
