# Generated by Django 5.1.1 on 2024-10-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Allowed_Response',
        ),
        migrations.RenameModel(
            old_name='UserOTP',
            new_name='OTPlogs',
        ),
        migrations.AlterModelOptions(
            name='allowed_response',
            options={'verbose_name': 'Allowed Response', 'verbose_name_plural': 'Allowed Response'},
        ),
        migrations.AlterModelOptions(
            name='annualincome',
            options={'verbose_name': 'Annual Income', 'verbose_name_plural': 'Annual Income'},
        ),
        migrations.AlterModelOptions(
            name='conditionalquestion',
            options={'verbose_name': 'Conditional Question', 'verbose_name_plural': 'Conditional Question'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Gender', 'verbose_name_plural': 'Gender'},
        ),
        migrations.AlterModelOptions(
            name='investmentamountperyear',
            options={'verbose_name': 'Investment Amount Per Year', 'verbose_name_plural': 'Investment Amount Per Year'},
        ),
        migrations.AlterModelOptions(
            name='maritalstatus',
            options={'verbose_name': 'Marital Status', 'verbose_name_plural': 'Marital Status'},
        ),
        migrations.AlterModelOptions(
            name='monthlysavingcapacity',
            options={'verbose_name': 'Monthly Saving Capacity', 'verbose_name_plural': 'Monthly Saving Capacity'},
        ),
        migrations.AlterModelOptions(
            name='occupation',
            options={'verbose_name': 'Occupation', 'verbose_name_plural': 'Occupation'},
        ),
        migrations.AlterModelOptions(
            name='otplogs',
            options={'verbose_name': 'OTP Logs', 'verbose_name_plural': 'OTP Logs'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Section'},
        ),
        migrations.AlterModelOptions(
            name='usercontactinfo',
            options={'verbose_name': 'User Contact Info', 'verbose_name_plural': 'User Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='userfinancialdetails',
            options={'verbose_name': 'User Financial Detail', 'verbose_name_plural': 'User Financial Details'},
        ),
        migrations.AlterModelOptions(
            name='userlogs',
            options={'verbose_name': 'User Logs', 'verbose_name_plural': 'User Logs'},
        ),
        migrations.AlterModelOptions(
            name='userpersonaldetails',
            options={'verbose_name': 'User Personal Detail', 'verbose_name_plural': 'User Personal Detail'},
        ),
        migrations.AlterModelOptions(
            name='userresponse',
            options={'verbose_name': 'User Response', 'verbose_name_plural': 'User Response'},
        ),
        migrations.AlterField(
            model_name='annualincome',
            name='income_category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='investmentamountperyear',
            name='investment_amount_per_year',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='status',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='monthlysavingcapacity',
            name='saving_category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='occupation',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='allowed_response',
            table='allowed_response',
        ),
        migrations.AlterModelTable(
            name='otplogs',
            table='otp_logs',
        ),
    ]
