# Generated by Django 5.1.1 on 2024-10-04 11:24

import app.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, validators=[app.models.validate_mobile_number])),
                ('email_id', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('ip_details', models.JSONField()),
                ('device_type', models.CharField(max_length=100)),
                ('last_access', models.DateTimeField()),
                ('action', models.CharField(choices=[('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('invalid', 'invalid_action')], default='invalid', max_length=10)),
            ],
            options={
                'db_table': 'user_logs',
                'indexes': [models.Index(fields=['email_id'], name='user_logs_email_i_942fc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[app.models.validate_mobile_number])),
                ('password', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_valid_till', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_management',
                'indexes': [models.Index(fields=['email'], name='user_manage_email_55611d_idx'), models.Index(fields=['mobile_number'], name='user_manage_mobile__620849_idx')],
            },
        ),
    ]
