# Generated by Django 5.1.1 on 2024-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userlogs_usermanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinancialdetails',
            name='investment_style',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Lump-Sum', 'Lump-Sum')], default='SIP', max_length=10),
        ),
        migrations.AlterField(
            model_name='userfinancialdetails',
            name='lock_in_period_accepted',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='userfinancialdetails',
            name='regular_source_of_income',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
