# Generated by Django 5.1.1 on 2024-10-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userfinancialdetails_investment_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='investmentamountperyear',
            name='investment_amount_per_year',
            field=models.CharField(choices=[('100000-250000', '100000-250000'), ('250000-500000', '250000-500000'), ('500000-1000000', '500000-1000000'), ('1000000-5000000', '1000000-5000000'), ('5000000+', '5000000+')], max_length=100),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced')], max_length=50),
        ),
    ]
