# Generated by Django 5.0.7 on 2024-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_userlogs_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlogs",
            name="email_id",
            field=models.EmailField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usermanagement",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
