# Generated by Django 5.1.1 on 2024-10-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_gender_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='investmentamountperyear',
            name='investment_amount_per_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
