# Generated by Django 5.1.1 on 2024-10-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_gender_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogs',
        ),
        migrations.DeleteModel(
            name='UserManagement',
        ),
    ]
