---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-mf-pipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-mf-pipe
  template:
    metadata:
      labels:
        app: ai-mf-pipe
    spec:
      containers:
      - name: ai-mf-pipe
        image: avisoft/ai-mf-backend:latest
        imagePullPolicy: Always
        workingDir: /AIMFBackend
        command: ["celery", "-A", "ai_mf_backend.celery_tasks", "worker", "--autoscale=$(CELERY_AUTOSCALE_UPPER_LIMIT),$(CELERY_AUTOSCALE_LOWER_LIMIT)", "--loglevel=$(LOG_LEVEL)"]
        envFrom:
        - configMapRef:
            name: ai-mf-config
        resources:
          requests:
            # cpu: 4000m
            memory: 2Gi
          limits:
            # cpu: 8000m
            memory: 6Gi
        volumeMounts:
        - name: datafiles
          mountPath: /AIMFBackend/ai_mf_backend/datafiles
      volumes:
      - name: datafiles
        emptyDir: {}  # For demonstration. Consider using a PersistentVolume in production.
