# Generated by Django 5.1.2 on 2024-11-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowed_response",
            name="option_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="allowed_response",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allowed_response",
            name="weight_per_option",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="question",
            name="base_weight",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="question",
            name="initial_weight",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="question_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="section",
            name="section_score",
            field=models.FloatField(default=0.0),
        ),
    ]
