# Generated by Django 5.1.2 on 2024-11-20 06:59

import ai_mf_backend.utils.v1.validators.status
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupation",
            name="occupation",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    ai_mf_backend.utils.v1.validators.status.validate_occupation
                ],
            ),
        ),
    ]
