# Generated by Django 5.1.2 on 2024-12-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ai_mf_backend', '0001_allowed_response_option_score_and_more'), ('ai_mf_backend', '0005_merge_20241219_1850'), ('ai_mf_backend', '0006_rename_weight_per_option_allowed_response_response_weight_and_more')]

    dependencies = [
        ('ai_mf_backend', 'constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowed_response',
            name='response_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='initial_question_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section',
            name='initial_section_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allowed_response',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionWeightsPerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_mf_backend.question')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_mf_backend.section')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_mf_backend.usercontactinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionWeightsPerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0.0)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_mf_backend.section')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_mf_backend.usercontactinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
