# Generated by Django 5.1.2 on 2024-11-06 12:30

import ai_mf_backend.utils.v1.validation.status
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_mf_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maritalstatus',
            name='marital_status',
            field=models.CharField(max_length=50, unique=True, validators=[ai_mf_backend.utils.v1.validation.status.validate_marital_status]),
        ),
    ]
