# Generated by Django 5.1.2 on 2024-11-06 09:56

import ai_mf_backend.utils.v1.validators.dates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpersonaldetails",
            name="add_date",
            field=models.DateTimeField(
                auto_now_add=True,
                validators=[
                    ai_mf_backend.utils.v1.validators.dates.validate_not_future_date
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userpersonaldetails",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    ai_mf_backend.utils.v1.validators.dates.validate_reasonable_birth_date,
                    ai_mf_backend.utils.v1.validators.dates.validate_not_future_date,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userpersonaldetails",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True,
                validators=[
                    ai_mf_backend.utils.v1.validators.dates.validate_not_future_date
                ],
            ),
        ),
    ]
