# Generated by Django 5.1.2 on 2024-12-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0001_reference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reference",
        ),
        migrations.AlterField(
            model_name="section",
            name="section",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
