# Generated by Django 5.1.2 on 2024-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowed_response",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conditionalquestion",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="section",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
