# Generated by Django 5.1.2 on 2024-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0001_allowed_response_option_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowed_response",
            name="position",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
