# Generated by Django 5.1.2 on 2024-11-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0002_alter_allowed_response_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowed_response",
            name="option_score",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_score",
            field=models.FloatField(default=1.0),
        ),
    ]
