# Generated by Django 5.1.2 on 2024-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0002_delete_reference_alter_section_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                ("column_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("projection_table_mapping", "projection_table_mapping")
                        ],
                        max_length=255,
                    ),
                ),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
