# Generated by Django 5.1.2 on 2024-11-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0003_alter_allowed_response_option_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="section_score",
            field=models.FloatField(default=1.0),
        ),
    ]
