# Generated by Django 5.1.2 on 2024-12-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0003_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontactinfo",
            name="questionnaire_filled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercontactinfo",
            name="user_details_filled",
            field=models.BooleanField(default=False),
        ),
    ]
