# Generated by Django 5.1.2 on 2024-12-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_mf_backend', '0001_squashed_initial'),
        ('ai_mf_backend', '0004_usercontactinfo_questionnaire_filled_and_more'),
    ]

    operations = [
    ]
