# Generated by Django 5.1.2 on 2024-12-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0001_allowed_response_option_score_and_more"),
        ("ai_mf_backend", "0004_usercontactinfo_questionnaire_filled_and_more"),
    ]

    operations = []
