# Generated by Django 5.1.2 on 2024-12-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mf_backend", "0004_usercontactinfo_questionnaire_filled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfinancialdetails",
            name="investment_style",
            field=models.CharField(
                blank=True,
                choices=[("SIP", "SIP"), ("Lump-Sum", "Lump-Sum")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userfinancialdetails",
            name="lock_in_period_accepted",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userfinancialdetails",
            name="regular_source_of_income",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                null=True,
            ),
        ),
    ]
